@preconcurrency import AVFoundation
import UIKit
import XCTest
@testable import Camelot

final class CameraPrecisionTests: XCTestCase {
    func testConsensusRejectsMovingForegroundAndDegenerateSupport() throws {
        let expected = CameraTransform(values: [1.04, -0.03, 0.02, 0.02, 1.04, -0.01, 0.025, -0.02, 1])
        var matches: [CameraFeatureRegistration.Match] = []
        for row in 0..<6 {
            for column in 0..<8 {
                let source = CGPoint(x: 0.08 + Double(column) * 0.11, y: 0.08 + Double(row) * 0.13)
                matches.append(.init(source: source, target: try XCTUnwrap(expected.point(source))))
            }
        }
        for i in 0..<20 {
            let source = CGPoint(x: 0.1 + Double(i % 5) * 0.14, y: 0.6 + Double(i / 5) * 0.08)
            matches.append(.init(source: source, target: .init(x: source.x - 0.08, y: source.y + 0.03)))
        }
        let fitted = try XCTUnwrap(CameraFeatureRegistration.consensus(matches, size: .init(width: 640, height: 360)))
        for source in GroundFieldOverlay.rectangle {
            let target = try XCTUnwrap(expected.point(source)), actual = try XCTUnwrap(fitted.point(source))
            XCTAssertEqual(actual.x, target.x, accuracy: 0.0001)
            XCTAssertEqual(actual.y, target.y, accuracy: 0.0001)
        }
        let line = (0..<20).map { i in
            let p = CGPoint(x: Double(i) / 20, y: 0.4)
            return CameraFeatureRegistration.Match(source: p, target: p)
        }
        XCTAssertNil(CameraFeatureRegistration.consensus(line, size: .init(width: 640, height: 360)))
    }

    @MainActor
    func testFlatGrassAndDifferentShotsDoNotProduceCameraTracks() throws {
        let format = UIGraphicsImageRendererFormat(); format.scale = 1
        let renderer = UIGraphicsImageRenderer(size: .init(width: 640, height: 360), format: format)
        let flat = renderer.image { ctx in UIColor.green.setFill(); ctx.fill(.init(x: 0, y: 0, width: 640, height: 360)) }
        XCTAssertNil(try CameraMotionTracking.registerScene(previous: try XCTUnwrap(flat.cgImage), current: try XCTUnwrap(flat.cgImage)))
        func image(_ seed: Int) -> CGImage {
            renderer.image { ctx in
                UIColor.darkGray.setFill(); ctx.fill(.init(x: 0, y: 0, width: 640, height: 360))
                for i in 0..<160 {
                    UIColor(hue: CGFloat(i % 17) / 17, saturation: 0.6, brightness: 0.9, alpha: 1).setFill()
                    ctx.fill(CGRect(x: (i * seed * 83) % 620, y: (i * seed * 47) % 340, width: 14 + i % 11, height: 12 + i % 19))
                }
            }.cgImage!
        }
        XCTAssertNil(try CameraMotionTracking.registerScene(previous: image(1), current: image(23)))
    }

    @MainActor
    func testCameraPanKeepsStaticLandmarksOnStressFootage() async throws {
        let url = URL.documentsDirectory.appending(path: "Recordings/EBB12192-62DB-495B-A6CE-218F0C420A74.mov")
        try XCTSkipIf(!FileManager.default.fileExists(atPath: url.path), "Requires fixture phone")
        let began = Date()
        let motion = try await CameraMotionTracking.track(url: url, from: 3, to: 32.9) { _ in }
        print("CAMERA_PRECISION elapsed=\(Date().timeIntervalSince(began)) samples=\(motion.samples.count) lost=\(String(describing: motion.lostAt))")
        let generator = AVAssetImageGenerator(asset: AVURLAsset(url: url))
        generator.appliesPreferredTrackTransform = true
        generator.requestedTimeToleranceBefore = .zero; generator.requestedTimeToleranceAfter = .zero
        let landmarks = [CGPoint(x: 0.531, y: 0.414), .init(x: 0.377, y: 0.401), .init(x: 0.418, y: 0.429)]
        // Hand-read fixed floodlight footing, doorway and far field corner in
        // exact source frames (not generated by the estimator under test).
        let expected: [Double: [CGPoint]] = [
            9: [.init(x: 0.8623, y: 0.3837), .init(x: 0.6963, y: 0.3663), .init(x: 0.7390, y: 0.3984)],
            13.8: [.init(x: 0.5610, y: 0.3880), .init(x: 0.4082, y: 0.3750), .init(x: 0.4492, y: 0.4028)]
        ]
        for time in [3.0, 5, 7, 9, 11, 13.8, 18, 23, 28, 32.8] {
            let transform = try XCTUnwrap(motion.transform(at: time))
            let points = landmarks.compactMap { transform.point($0) }
            print("CAMERA_LANDMARKS time=\(time) points=\(points)")
            if let expected = expected[time] {
                for (actual, target) in zip(points, expected) {
                    let error = hypot((actual.x - target.x) * 1920, (actual.y - target.y) * 1080)
                    print("CAMERA_LANDMARK_ERROR time=\(time) pixels1080p=\(error)")
                    XCTAssertLessThan(error, 10, "Static field/background landmark drift")
                }
            }
            let source = try await generator.image(at: CMTime(seconds: time, preferredTimescale: 600)).image
            let frame = CGRect(x: 0, y: 0, width: source.width, height: source.height)
            let rendered = UIGraphicsImageRenderer(size: frame.size).image { renderer in
                UIImage(cgImage: source).draw(in: frame)
                renderer.cgContext.setStrokeColor(UIColor.cyan.cgColor); renderer.cgContext.setLineWidth(3)
                for point in points {
                    let p = CGPoint(x: point.x * frame.width, y: point.y * frame.height)
                    renderer.cgContext.strokeEllipse(in: CGRect(x: p.x - 10, y: p.y - 10, width: 20, height: 20))
                }
            }
            let attachment = XCTAttachment(image: rendered); attachment.name = "Camera static landmarks at \(time)s"; attachment.lifetime = .keepAlways; add(attachment)
        }
        XCTAssertNil(motion.lostAt)
    }

    @MainActor
    func testBackgroundRegistrationPreservesZoomAndRoll() throws {
        let size = CGSize(width: 640, height: 360)
        let format = UIGraphicsImageRendererFormat(); format.scale = 1
        let renderer = UIGraphicsImageRenderer(size: size, format: format)
        let source = renderer.image { ctx in
            UIColor.darkGray.setFill(); ctx.fill(CGRect(origin: .zero, size: size))
            for i in 0..<160 {
                UIColor(hue: CGFloat(i % 17) / 17, saturation: 0.6, brightness: 0.5 + CGFloat(i % 3) * 0.2, alpha: 1).setFill()
                ctx.fill(CGRect(x: (i * 83) % 620, y: (i * 47) % 340, width: 14 + i % 11, height: 12 + i % 19))
            }
        }
        let affine = CGAffineTransform(translationX: 320 + 9, y: 180 - 4).rotated(by: 0.035).scaledBy(x: 1.055, y: 1.055).translatedBy(x: -320, y: -180)
        let current = renderer.image { ctx in ctx.cgContext.concatenate(affine); source.draw(at: .zero) }
        let same = try XCTUnwrap(CameraMotionTracking.registerScene(previous: try XCTUnwrap(source.cgImage), current: try XCTUnwrap(source.cgImage)))
        for point in GroundFieldOverlay.rectangle {
            let mapped = try XCTUnwrap(same.point(point))
            XCTAssertEqual(mapped.x, point.x, accuracy: 0.00001)
            XCTAssertEqual(mapped.y, point.y, accuracy: 0.00001)
        }
        let transform = try XCTUnwrap(CameraMotionTracking.registerScene(previous: try XCTUnwrap(source.cgImage), current: try XCTUnwrap(current.cgImage)))
        for point in [CGPoint(x: 0.2, y: 0.2), .init(x: 0.8, y: 0.2), .init(x: 0.5, y: 0.85)] {
            let expected = CGPoint(x: point.x * 640, y: point.y * 360).applying(affine)
            let actual = try XCTUnwrap(transform.point(point))
            let error = hypot(actual.x * 640 - expected.x, actual.y * 360 - expected.y)
            print("CAMERA_ZOOM_ROLL errorPixels=\(error)")
            XCTAssertLessThan(error, 2)
        }
    }

    @MainActor
    func testGroundRegistrationFollowsThePitchWhenTheStandsMoveTheOtherWay() throws {
        let size = CGSize(width: 640, height: 360)
        let format = UIGraphicsImageRendererFormat(); format.scale = 1
        let renderer = UIGraphicsImageRenderer(size: size, format: format)
        func picture(stand: CGFloat, field: CGFloat) -> CGImage {
            renderer.image { ctx in
                UIColor(red: 0.15, green: 0.45, blue: 0.12, alpha: 1).setFill()
                ctx.fill(CGRect(origin: .zero, size: size))
                for row in 0..<8 {
                    for column in 0..<16 {
                        let green = (row + column).isMultiple(of: 2)
                        UIColor(red: 0.1, green: green ? 0.55 : 0.32, blue: 0.08, alpha: 1).setFill()
                        ctx.fill(CGRect(x: field + CGFloat(column) * 40, y: 150 + CGFloat(row) * 26, width: 40, height: 26))
                    }
                }
                UIColor.white.setFill()
                for column in 0..<8 {
                    ctx.fill(CGRect(x: field + 20 + CGFloat(column) * 80, y: 150, width: 3, height: 210))
                }
                for row in 0..<4 {
                    ctx.fill(CGRect(x: field, y: 180 + CGFloat(row) * 50, width: 640, height: 3))
                }
                for i in 0..<40 {
                    UIColor(hue: CGFloat(i % 9) / 9, saturation: 0.4, brightness: 0.35, alpha: 1).setFill()
                    ctx.fill(CGRect(x: stand + CGFloat((i * 37) % 600), y: CGFloat((i * 19) % 120), width: 28, height: 16))
                }
            }.cgImage!
        }
        let previous = try XCTUnwrap(CameraFeatureRegistration.Frame(picture(stand: 0, field: 0)))
        let current = try XCTUnwrap(CameraFeatureRegistration.Frame(picture(stand: -14, field: 8)))
        let transform = try XCTUnwrap(CameraFeatureRegistration.register(previous: previous, current: current, initial: .identity))
        let moved = try XCTUnwrap(transform.point(CGPoint(x: 0.5, y: 0.75)))
        XCTAssertEqual(moved.x, 0.5 + 8 / 640, accuracy: 0.008, "Floor drawings follow the grass, not the stands")
        XCTAssertGreaterThan(moved.x, 0.5)
    }

    @MainActor
    func testChainedCameraKeepsAPlayerThroughAPanTheDirectWarpRejects() throws {
        let size = CGSize(width: 640, height: 360)
        let format = UIGraphicsImageRendererFormat(); format.scale = 1
        let renderer = UIGraphicsImageRenderer(size: size, format: format)
        func frame(_ shift: CGFloat) -> CameraFeatureRegistration.Frame {
            let image = renderer.image { ctx in
                UIColor(red: 0.12, green: 0.42, blue: 0.1, alpha: 1).setFill()
                ctx.fill(CGRect(origin: .zero, size: size))
                for row in 0..<9 {
                    for column in 0..<16 {
                        UIColor(red: 0.08, green: (row + column).isMultiple(of: 2) ? 0.58 : 0.3, blue: 0.07, alpha: 1).setFill()
                        ctx.fill(CGRect(x: shift + CGFloat(column) * 42 - 40, y: CGFloat(row) * 40, width: 42, height: 40))
                    }
                }
                UIColor.white.setFill()
                for column in 0..<10 {
                    ctx.fill(CGRect(x: shift + CGFloat(column) * 70, y: 40, width: 4, height: 280))
                }
            }.cgImage!
            return CameraFeatureRegistration.Frame(image)!
        }
        let step: CGFloat = 40
        var camera = IncrementalSceneCamera()
        var last: CameraTransform?
        let first = frame(0)
        for index in 0...4 {
            last = camera.observe(frame(CGFloat(index) * step), at: Double(index) * 0.05)
        }
        let transform = try XCTUnwrap(last)
        let moved = try XCTUnwrap(transform.point(CGPoint(x: 0.3, y: 0.6)))
        let expectedX = 0.3 + Double(4 * step) / 640
        XCTAssertEqual(moved.x, expectedX, accuracy: 0.03)
        if let direct = try? CameraMotionTracking.register(previous: first.image, current: frame(4 * step).image),
           let once = direct.point(CGPoint(x: 0.3, y: 0.6)) {
            XCTAssertGreaterThan(abs(once.x - expectedX), 0.05, "One warp does not carry a player across this pan")
        }
    }
}
